[package]
name = "m3u8-rs"
version = "1.0.0"
authors = ["Rutger"]
readme = "README.md"
repository = "https://github.com/rutgersc/m3u8-rs"
description = "A library for parsing m3u8 files (Apple's HTTP Live Streaming (HLS) protocol)."

[dependencies]
nom = "^1.2.3"
